export const routes = {
  home: "/",
  article: (id: string | number) => `/article/${id}`,
  articles: "/articles",
  authors: "/authors",
  topics: "/topics",
  about: "/about",
  signin: "/signin",
  register: "/register",
  dashboard: "/dashboard",
  submissions: "/dashboard/submissions",
  submissionById: (id: string) => `/dashboard/submissions/${id}`,
  submissionDecision: (id: string, decision: string) => `/dashboard/submissions/${id}/decision/${decision}`,
  submissionCreate: "/dashboard/submissions/new",
  reviews: "/dashboard/reviews",
  editorial: "/dashboard/editorial",
  editorialDecision: "/dashboard/editorial-decision",
  reviewerAssignment: "/dashboard/reviewer-assignment",
  plagiarism: "/dashboard/plagiarism",
  production: "/dashboard/production",
  layoutFiles: "/dashboard/layout-files",
  published: "/dashboard/published",
  volumes: "/dashboard/volumes",
  doiManagement: "/dashboard/doi",
  users: "/dashboard/users",
  reports: "/dashboard/reports",
  settings: "/dashboard/settings",
  payment: "/dashboard/payment",
  payments: "/dashboard/payments",
  notifications: "/dashboard/notifications",
  profile: "/dashboard/profile",
  submissionEdit: (id: string) => `/dashboard/submissions/${id}/edit`,
  editor: "/dashboard/editor",
  editorById: (id: string | number) => `/dashboard/editor/${id}`,
};
